version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g yarn
      - yarn
  build:
    commands:
      - npx eas build -p android --non-interactive
