version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g eas-cli
      - npm i
  build:
    commands:
      - echo "EXPO_TOKEN = $EXPO_TOKEN"
      - node pre-build.js
      - npx eas build -p android --non-interactive
